name: deploy vite-press
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Build
        run: |
          npm install yarn -g
          yarn
          yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
